---
title: Liberty Restored, Newport, South Wales
timezone: UTC
collections:
  authors:
    title: Authors
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Liberty Restored - Healthy People, Healthy Families, Healthy City.
url: https://www.libertyrestored.co.uk
author: Liberty Church
twitter:
  username: LibertyChurchUK
facebook:
  app_id: 
  publisher: 
  admins: 
logo: "/images/logos/liberty-church-logo.png"
lang: en-GB
social:
  links:
  - https://www.facebook.com/libertyrestoreduk
paginate: 12
paginate_path: "/blog/page:num/"
sass:
  style: :compressed
gems:
- jekyll-sitemap
- jekyll-seo-tag
